name: Deploy to Vercel

on:
  push:
    branches:
      - master # Adjust this to match your default branch if necessary

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust the Node.js version as needed
          # cache: 'yarn'

      # Install Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Deploy server
      - name: Deploy server
        working-directory: ./server
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # Deploy client
      - name: Deploy client
        working-directory: ./client/v2
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
